version: "3.7"
services: 
  cacher:
    build: ./cacher
    image: cacher:dev
    restart: on-failure:5
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
        delay: 5s
    depends_on: 
      - redis
  webapp:
    build: ./webapp
    image: webapp:dev
    ports: 
      - "8050:8050"
    depends_on: 
      - redis
  redis:
    image: redis:5.0.7-alpine
    restart: always
    ports: 
      - "6379:6379"