version: "3.7"
services: 
  cacher:
    build: ./cacher
    image: cacher:dev
    restart: on-failure:5
    depends_on: 
      - redis
  redis:
    image: redis:5.0.7-alpine
    ports: 
      - "6379:6379"